# Render deployment configuration
services:
  - type: web
    name: alfuttaim-ikea-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: JUSPAY_API_KEY
        sync: false
      - key: MERCHANT_ID
        sync: false